[package]
name = "hello_world_flavor1"
version = "0.1.0"
authors = ["Kokou Koumagna <kokou.koumagnagottoh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
